title:       "System Programming 2023-1 (SP231)"
version:     "1"
copyright:   "2023-2023"
description: >- 
  SP class is fun ngl
google_analytics: "UA-89852122-13"
author:           "ReeyaDono"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://reeyadono.github.io/sp231/"
urlcontact:       "TBS"
urlgithub:        "https://github.com/ReeyaDono/sp231"
urlghpage:        "https://reeyadono.github.io/sp231/"
keywords:         "jekyll, testing"
github:           
  - metadata

